version: '3.3'
services:
    S-Shot-as-a-service:
        dns: 
          - 8.8.8.8
          - 1.1.1.1
        restart: unless-stopped
        ports:
            - '8287:8080'
        build:
          context: ./
          dockerfile: Dockerfile
